#!/usr/bin/bash
if [[ "$(hostnamectl)" == *"Ubuntu"* ]]; then
    echo "Ubuntu";
    # Fish
    apt-get install -y fish;
    chsh -s /usr/bin/fish;

    # Emacs
    add-apt-repository ppa:kelleyk/emacs;
    apt update;
    apt install -y emacs26;
    git clone https://github.com/hlissner/doom-emacs ~/.emacs.d;
    ~/.emacs.d/bin/doom install;

    # Font
    apt-get install -y unzip;
    mkdir ~/.fonts;
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Iosevka.zip ~/.fonts/Iosevka.zip;
    cd ~/.fonts;
    unzip ~/Iosevka.zip;
    fc-cache -f -v;
    rm ~/Iosevka.zip;

    # Languages
    apt-get install -y cmake;
    apt install -y python3-pip;

    curl -s https://sirbubbls.github.io/dotfiles/scripts/setup_dotfiles | bash;

    curl -L https://get.oh-my.fish | fish;
    omf install -y bobthefish;
else
    echo "Unsupported";
fi
